export const FETCH_BOOKINGS = 'FETCH_BOOKINGS';
export const DELETE_BOOKING = 'DELETE_BOOKING';
export const SET_TOTAL_PAGES = 'SET_TOTAL_PAGES';
export const CHANGE_CURRENT_PAGE = 'CHANGE_CURRENT_PAGE';
export const PREVIOUS_PAGE = 'PREVIOUS_PAGE';
export const NEXT_PAGE = 'NEXT_PAGE';
